# Generated by Django 5.2.4 on 2025-08-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_user_alter_appointments_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Person",
        ),
    ]
